# Welcome to Jekyll!

# Website settings
title: "Mohamed Chnafy"
description: "Resume"
keywords: ""
url: "https://depture.github.io"
baseurl: "/OnlineResume/"

# author
author:
  name: 'Mohamed Chnafy'
  first_name: 'Mohamed'
  last_name: 'Chnafy'
  email: 'chnafy62@gmail.com'
  facebook_username: ''
  github_username: ''
  avatar: 'static/img/landing/portrait0.png'
  desc: 'I am a data scientist with a strong background in mathematics, with data mining, machine learning and coding experience. \n
  Through academic and profesionnal projects, I gained significant data mining, machine learning and coding experience. \n
  Life is a continuous learning process, so work makes me more rigorous'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
